### ISSUE TITLE
Attack Scripts

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/mulsi#2]
## Description

Make some scripts and modules to easily reproduce attacks.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and tests are written
* [ ] The code was reviewed

## Tasks

* [x] Create a basic FGSM attack
* [ ] Create a script to scale the attack
