### ISSUE TITLE
Add BERT-Attack on text modality

### ISSUE THREAD

**Issue by imenelydiaker** [Xmaster6y/mulsi#4]
## Description

Attacking the text modality with [BERT-Attack](https://arxiv.org/abs/2004.09984). The attack was initially developed on BERT, thus it should be adapted to the targeted LLM.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] Develop the attack.
* [ ] Test script for the attack.
