### ISSUE TITLE
[EXPERIMENT] Detect concepts using images

### ISSUE THREAD

**Issue by imenelydiaker** [Xmaster6y/mulsi#5]
## Description

Detect concepts activated by the attack using images instead of text when building contrast vectors.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] Select concepts to work on.
* [ ] Gather a set of images for each selected concept.
* [ ] Build the contrast vectors.
