### ISSUE TITLE
[EXPERIMENT] Expand the list of model to evaluate

### ISSUE THREAD

**Issue by imenelydiaker** [Xmaster6y/mulsi#6]
## Description

Expand the list of models to attack and evaluate the detection method on. The idea is to verify the effectiveness of the detection method. 
And if possible, see if the some patterns appear when different models are attacked by different methods.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] List models and build processors.
* [ ] Attack the models and perform detection.
* [ ] Analyze results.
