### ISSUE TITLE
Contrast Reading Script

### ISSUE THREAD

**Issue by Xmaster6y** [Xmaster6y/mulsi#7]
## Description

Make some scripts and modules to easily scale reading.

## Acceptance Criterion

* [x] The code is documented
* [x] Utilities and tests are written
* [x] The code was reviewed

## Tasks

* [x] Create a basic contrast reading
* [x] Create a script to scale the reading
