### ISSUE TITLE
Extend concept reading with datasets

### ISSUE THREAD

**Issue by imenelydiaker** [Xmaster6y/mulsi#8]
## Description

Extend concept reading with text datasets.

## Acceptance Criterion

* [ ] The code is documented
* [ ] Utilities and class test are written
* [ ] The code was reviewed

## Tasks

* [ ] Collect datasets.
* [ ] Compute dataset representation with class `Representation`.
* [ ] Extend script to evaluate on a dataset.
